"""initial schema

Revision ID: 38f06fc31d15
Revises: 
Create Date: 2025-12-04 19:45:42.078068+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38f06fc31d15'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('subscription_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marketplace_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('marketplace_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_key_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_provider_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_monthly_token_limit', sa.Integer(), nullable=True),
    sa.Column('ai_tokens_used_this_month', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('azure_tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('graph_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_azure_tenant_id'), 'tenant', ['azure_tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_marketplace_subscription_id'), 'tenant', ['marketplace_subscription_id'], unique=False)
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=False)
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('api_key',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('allowed_ips', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_expires_at'), 'api_key', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_key_key_hash'), 'api_key', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_key_key_prefix'), 'api_key', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_key_name'), 'api_key', ['name'], unique=False)
    op.create_index(op.f('ix_api_key_tenant_id'), 'api_key', ['tenant_id'], unique=False)
    op.create_table('campaign',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detection_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=True),
    sa.Column('template_subject_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('unique_senders', sa.Integer(), nullable=False),
    sa.Column('source_organization', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_template_hash'), 'campaign', ['template_hash'], unique=False)
    op.create_index(op.f('ix_campaign_tenant_id'), 'campaign', ['tenant_id'], unique=False)
    op.create_table('category',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_category_tenant_name')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    op.create_index(op.f('ix_category_tenant_id'), 'category', ['tenant_id'], unique=False)
    op.create_table('contact',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_contact_at', sa.DateTime(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_contact_tenant_email')
    )
    op.create_index(op.f('ix_contact_email'), 'contact', ['email'], unique=False)
    op.create_index(op.f('ix_contact_tenant_id'), 'contact', ['tenant_id'], unique=False)
    op.create_table('custom_field_definition',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_searchable', sa.Boolean(), nullable=False),
    sa.Column('is_visible_in_list', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'field_key', name='uq_field_tenant_key')
    )
    op.create_index(op.f('ix_custom_field_definition_is_searchable'), 'custom_field_definition', ['is_searchable'], unique=False)
    op.create_index(op.f('ix_custom_field_definition_name'), 'custom_field_definition', ['name'], unique=False)
    op.create_index(op.f('ix_custom_field_definition_tenant_id'), 'custom_field_definition', ['tenant_id'], unique=False)
    op.create_table('form',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('styling', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_name'), 'form', ['name'], unique=False)
    op.create_index(op.f('ix_form_slug'), 'form', ['slug'], unique=False)
    op.create_index(op.f('ix_form_tenant_id'), 'form', ['tenant_id'], unique=False)
    op.create_table('role',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('azure_ad_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_role_tenant_name')
    )
    op.create_index(op.f('ix_role_azure_ad_group_id'), 'role', ['azure_ad_group_id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.create_index(op.f('ix_role_tenant_id'), 'role', ['tenant_id'], unique=False)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('azure_ad_oid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_azure_ad_oid'), 'user', ['azure_ad_oid'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_tenant_id'), 'user', ['tenant_id'], unique=False)
    op.create_table('workflow',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('trigger', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_name'), 'workflow', ['name'], unique=False)
    op.create_index(op.f('ix_workflow_tenant_id'), 'workflow', ['tenant_id'], unique=False)
    op.create_table('contact_field_value',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('field_definition_id', sa.Uuid(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_option', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_options', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['field_definition_id'], ['custom_field_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'field_definition_id', name='uq_contact_field')
    )
    op.create_index(op.f('ix_contact_field_value_contact_id'), 'contact_field_value', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_field_value_field_definition_id'), 'contact_field_value', ['field_definition_id'], unique=False)
    op.create_index(op.f('ix_contact_field_value_value_option'), 'contact_field_value', ['value_option'], unique=False)
    op.create_table('form_field',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_id', sa.Uuid(), nullable=False),
    sa.Column('field_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('placeholder', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('help_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conditional_logic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('maps_to_contact_field', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('maps_to_custom_field_id', sa.Uuid(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['maps_to_custom_field_id'], ['custom_field_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_field_form_id'), 'form_field', ['form_id'], unique=False)
    op.create_table('message',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('sender_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('is_template_match', sa.Boolean(), nullable=False),
    sa.Column('template_similarity_score', sa.Float(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_campaign_id'), 'message', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_message_contact_id'), 'message', ['contact_id'], unique=False)
    op.create_index(op.f('ix_message_external_id'), 'message', ['external_id'], unique=False)
    op.create_index(op.f('ix_message_is_template_match'), 'message', ['is_template_match'], unique=False)
    op.create_index(op.f('ix_message_processing_status'), 'message', ['processing_status'], unique=False)
    op.create_index(op.f('ix_message_received_at'), 'message', ['received_at'], unique=False)
    op.create_index(op.f('ix_message_sender_email'), 'message', ['sender_email'], unique=False)
    op.create_index(op.f('ix_message_tenant_id'), 'message', ['tenant_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('analysis',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sentiment_confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_response', sa.Text(), nullable=True),
    sa.Column('ai_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_ai_provider'), 'analysis', ['ai_provider'], unique=False)
    op.create_index(op.f('ix_analysis_message_id'), 'analysis', ['message_id'], unique=True)
    op.create_table('form_submission',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('field_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('utm_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spam_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_form_submission_contact_id'), 'form_submission', ['contact_id'], unique=False)
    op.create_index(op.f('ix_form_submission_form_id'), 'form_submission', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_submission_submitted_at'), 'form_submission', ['submitted_at'], unique=False)
    op.create_table('message_category',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('message_id', 'category_id')
    )
    op.create_table('workflow_execution',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actions_executed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_execution_message_id'), 'workflow_execution', ['message_id'], unique=False)
    op.create_index(op.f('ix_workflow_execution_triggered_at'), 'workflow_execution', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_workflow_execution_workflow_id'), 'workflow_execution', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_execution_workflow_id'), table_name='workflow_execution')
    op.drop_index(op.f('ix_workflow_execution_triggered_at'), table_name='workflow_execution')
    op.drop_index(op.f('ix_workflow_execution_message_id'), table_name='workflow_execution')
    op.drop_table('workflow_execution')
    op.drop_table('message_category')
    op.drop_index(op.f('ix_form_submission_submitted_at'), table_name='form_submission')
    op.drop_index(op.f('ix_form_submission_form_id'), table_name='form_submission')
    op.drop_index(op.f('ix_form_submission_contact_id'), table_name='form_submission')
    op.drop_table('form_submission')
    op.drop_index(op.f('ix_analysis_message_id'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_ai_provider'), table_name='analysis')
    op.drop_table('analysis')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_message_tenant_id'), table_name='message')
    op.drop_index(op.f('ix_message_sender_email'), table_name='message')
    op.drop_index(op.f('ix_message_received_at'), table_name='message')
    op.drop_index(op.f('ix_message_processing_status'), table_name='message')
    op.drop_index(op.f('ix_message_is_template_match'), table_name='message')
    op.drop_index(op.f('ix_message_external_id'), table_name='message')
    op.drop_index(op.f('ix_message_contact_id'), table_name='message')
    op.drop_index(op.f('ix_message_campaign_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_form_field_form_id'), table_name='form_field')
    op.drop_table('form_field')
    op.drop_index(op.f('ix_contact_field_value_value_option'), table_name='contact_field_value')
    op.drop_index(op.f('ix_contact_field_value_field_definition_id'), table_name='contact_field_value')
    op.drop_index(op.f('ix_contact_field_value_contact_id'), table_name='contact_field_value')
    op.drop_table('contact_field_value')
    op.drop_index(op.f('ix_workflow_tenant_id'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_name'), table_name='workflow')
    op.drop_table('workflow')
    op.drop_index(op.f('ix_user_tenant_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_azure_ad_oid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_tenant_id'), table_name='role')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_azure_ad_group_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_form_tenant_id'), table_name='form')
    op.drop_index(op.f('ix_form_slug'), table_name='form')
    op.drop_index(op.f('ix_form_name'), table_name='form')
    op.drop_table('form')
    op.drop_index(op.f('ix_custom_field_definition_tenant_id'), table_name='custom_field_definition')
    op.drop_index(op.f('ix_custom_field_definition_name'), table_name='custom_field_definition')
    op.drop_index(op.f('ix_custom_field_definition_is_searchable'), table_name='custom_field_definition')
    op.drop_table('custom_field_definition')
    op.drop_index(op.f('ix_contact_tenant_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_email'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_category_tenant_id'), table_name='category')
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_campaign_tenant_id'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_template_hash'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_name'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_api_key_tenant_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_name'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_key_prefix'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_key_hash'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_expires_at'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_marketplace_subscription_id'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_azure_tenant_id'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
